version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: course_work_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: course_work
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
