logging:
  level:
    org:
      #      hibernate:
      #        type:
      #          descriptor:
      #            sql:
      #              BasicBinder: TRACE
      #        SQL: DEBUG
      springframework:
        .: DEBUG
        security:
          .: DEBUG
          oauth2: DEBUG
pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n"

task:
  assignCargoToFlightSeconds: 15

server:
  error:
    include-message: always
  servlet:
    context-path: /api
  port: ${BACKEND_PORT:8079}
  address: ${BACKEND_URL:0.0.0.0}

socket:
  host: ${SOCKET_HOST:0.0.0.0}
  port: ${SOCKET_PORT:8087}

spring:
  application:
    name: course_work
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
    password: ${POSTGRES_CONNECT_PASSWORD}
    url: ${POSTGRES_CONNECT_URL}
    username: ${POSTGRES_CONNECT_USER}
  flyway:
    baseline-on-migrate: true
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
      org:
        hibernate:
          envers:
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
            audit_table_suffix: _audit
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: backend
            client-secret: CfXvdW88ft1bFPUGpCZIfKEl1YLiN0xV
            authorization-grant-type: password
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/realms/refactoring
#        provider:
#          keycloak:
#            issuer-uri: http://keycloak:8080/realms/refactoring

springdoc:
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health