CREATE TABLE is_course_refresh_storage
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    refresh_token VARCHAR(4096),
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_is_course_refresh_storage PRIMARY KEY (id)
);