CREATE TABLE is_course_ship_status
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ship_id       BIGINT           NOT NULL,
    fuel_level    DOUBLE PRECISION NOT NULL,
    engine_status VARCHAR(50)      NOT NULL,
    last_updated  TIMESTAMP        NOT NULL,
    fuel_status   VARCHAR(255)     NOT NULL,
    FOREIGN KEY (ship_id) REFERENCES is_course_ship (id)
);

alter table is_course_flight
    add booked_seats int not null default 0,
    add total_seats  int not null default 0;